### ISSUE TITLE
icons in dock is so big of gnome 40.

### ISSUE THREAD

**Issue by bytecho** [vinceliuice/Fluent-gtk-theme#10]
In gnome 40 overview, icons in dock is very big. I think if decreasing icons' size will be better.

**Comment by vinceliuice** [comment]
Gnome 40 is not support yet

**Comment by bytecho** [comment]
> Gnome 40 is not support yet

Got it. And thanks for your work, it's a very pretty theme.

**Comment by vinceliuice** [comment]
Supported now!

**Comment by AshkanLaei** [comment]
Is this problem fixed in compact mode? I don't have problems in normal modes but dock is too big in compact mode.

Using `Fluent` theme:
![Fluent](https://user-images.githubusercontent.com/50172698/121191660-6c67a400-c881-11eb-89b9-40a255e64db4.png)
Using `Fluent-compact` theme:
![Fluent-compact](https://user-images.githubusercontent.com/50172698/121191808-8f925380-c881-11eb-8c45-58667b85318c.png)

**Comment by vinceliuice** [comment]
I'll check this!
