### ISSUE TITLE
Checkboxes looks weird on Xfce

### ISSUE THREAD

**Issue by NotteShock** [vinceliuice/Fluent-gtk-theme#80]
The checkboxes looks weird in this screenshot. I also tried restarting and it still look weird like that.
![IMG_20211226_080958](https://user-images.githubusercontent.com/85934291/147396432-04239e77-d367-42c1-9889-7323564e69be.jpg)

**Comment by vinceliuice** [comment]
Assets file missing, make sure you have installed `p7zip` `p7zip-full` `p7zip-rar` before you unzipping the zip file, because if there is no p7zip when you unzipping zip files you will loss all permission of the linux files, that will causes the link file to become invalid, and the image files not authorized to read

**Comment by vinceliuice** [comment]
You can download this gz files: https://github.com/vinceliuice/Fluent-gtk-theme/archive/refs/tags/2021-12-20.tar.gz , this one has no such issue on linux
